steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/places-api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/places-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'places-api'
      - '--image=gcr.io/$PROJECT_ID/places-api'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8070'
      - '--set-env-vars=GOOGLE_API_KEY=$_GOOGLE_API_KEY,CORS_ALLOWED_ORIGIN=$_CORS_ALLOWED_ORIGIN'

substitutions:
  _GOOGLE_API_KEY: ''
  _CORS_ALLOWED_ORIGIN: ''

images:
  - 'gcr.io/$PROJECT_ID/places-api'
